before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    binary: vcreport
    ldflags:
      - -s -w -X github.com/invit/vcreport/internal/lib/version.Version={{.Version}} -X github.com/invit/vcreport/internal/lib/version.Commit={{.Commit}} -X github.com/invit/vcreport/internal/lib/version.Date={{.Date}}
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
archives:
  - files:
    - LICENSE
#    - README.md
checksum:
  name_template: 'checksums.txt'
dockers:
  -
    goos: linux
    goarch: amd64
    binaries:
      - vcreport
    image_templates:
      - "ghcr.io/invit/vcreport/vcreport:latest"
      - "ghcr.io/invit/vcreport/vcreport:{{ .Tag }}"
    dockerfile: Dockerfile
    build_flag_templates:
      - "--pull"
